# Nixpacks config for CLG-DEPLOY (main user-facing app)
# This builds the root-level Vite app

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npm run build",
  "chmod +x inject-config.sh",
  "BACKEND_URL=\"${BACKEND_URL:-}\" ./inject-config.sh"
]

[start]
cmd = "node serve-spa.js"
