# Railway monorepo configuration
# This file defines service locations in the monorepo

[build]
builder = "NIXPACKS"
watchPatterns = ["apps/backend/**"]

[deploy]
startCommand = "cd apps/backend && npm run start"
healthcheckPath = "/healthz"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
